<?xml version="1.0" encoding="UTF-8"?><testrun name="UsuarioWSTest" project="leiloes-rest-assured" tests="5" started="5" failures="0" errors="1" ignored="0">
  <testsuite name="br.com.caelum.leilao.teste.UsuarioWSTest" time="3.406">
    <testcase name="deveRetornarUsuarioPeloId" classname="br.com.caelum.leilao.teste.UsuarioWSTest" time="2.256"/>
    <testcase name="deveRetornarListaComTodosUsuarios" classname="br.com.caelum.leilao.teste.UsuarioWSTest" time="0.455"/>
    <testcase name="deveRetornarListaDeUsuarios" classname="br.com.caelum.leilao.teste.UsuarioWSTest" time="0.221"/>
    <testcase name="deveDeletarUsuarioPeloId" classname="br.com.caelum.leilao.teste.UsuarioWSTest" time="0.053">
      <error>com.jayway.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at com.jayway.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:836)
	at com.jayway.restassured.path.json.JsonPath$1.doParseWith(JsonPath.java:758)
	at com.jayway.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:877)
	at com.jayway.restassured.path.json.JsonPath.getJsonObject(JsonPath.java:843)
	at com.jayway.restassured.path.json.JsonPath.getObject(JsonPath.java:501)
	at br.com.caelum.leilao.teste.UsuarioWSTest.deveDeletarUsuarioPeloId(UsuarioWSTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '&lt;', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:82)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at com.jayway.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:92)
	at com.jayway.restassured.path.json.JsonPath$1$1.method(JsonPath.java:760)
	at com.jayway.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:834)
	... 29 more

</error>
    </testcase>
    <testcase name="deveAdicionarUmUsuario" classname="br.com.caelum.leilao.teste.UsuarioWSTest" time="0.421"/>
  </testsuite>
</testrun>
